language: d
sudo: required
dist: xenial


matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.085.0
    - d: dmd-2.084.1
    - d: ldc-1.14.0
    - d: ldc-1.13.0
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    packages:
      - libnanomsg-dev

script:
  dub test --compiler=${DC} -- -d -s ~@notravis

after_success:
 - bash <(curl -s https://codecov.io/bash)
