language: d
sudo: false

apt_packages:
  - cmake

install:
  - git clone https://github.com/nanomsg/nanomsg.git
  - cd nanomsg
  - cmake -DNN_STATIC_LIB=on .
  - make -j`nproc`
  - export LD_LIBRARY_PATH=$PWD
  - cd -

matrix:
    include:
        - d: dmd
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.070.2
        - d: ldc
        - d: ldc-1.0.0
