language: d
sudo: required

apt_packages:
  - cmake

install:
  - git clone https://github.com/nanomsg/nanomsg.git
  - pushd nanomsg
  - cmake .
  - make -j`nproc`
  - sudo make install
  - sudo ldconfig
  - popd

script:
  - dub test -- -s  # nanomsg has problems with threads
  - dub build
  - make -C examples

matrix:
    include:
        - d: dmd
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.070.2
        - d: ldc
        - d: ldc-1.0.0
